spring:
  application:
    name: demo3
  datasource:
    url: jdbc:mysql://39.98.185.226:30002/javaweb
    username: ${DATA_BASE_USERNAME}
    password: ${DATA_BASE_PASSWORLD}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8081
